ckpt_path: /path/to/checkpoint.ckpt   # Absolute path for model checkpoint
classes: [na, nuclei, cyto, rbc, mp]  # Classes model predicts
augmentation:
   base_aug_cf:
      get_third_channel_params:
         mode: three_channels     # SRH image preprocessing method (default three_channels)
         subtracted_base: 5000    # Constant to specify basae intensity for red color channel (default 5000)   
   train_strong_aug_cf:
      p: 0                        # Likelihood of applying each training augmentation
      augs: []                    # List of training augmentations (options listed in `get_strong_aug` function in `ds/datasets/db_improc.py`)
   val_strong_aug_cf: same        # Can use `same` to copy `augmentation/train_strong_aug_cf` configuration
inference_batch_size: 16          # Number of data samples in ech inference batch      
confidence: 0.5                   # Detection threshold after nms
device: cuda                      # Hardware to run inference on (cuda, cpu)

inference_dir: /path/to/patches   # Absolute path for input images directory
out_dir: /path/to/output          # Absolute path for output directory
